//----------------------------------------------
//
//        Sketch Generated by Visuino
//              www.visuino.com
//          Version  7.8.2.230
//
//----------------------------------------------

#define VISUINO_ESP32

#include <OpenWire.h>
#include <Mitov.h>
#include <Mitov_FormattedSerial.h>
#include <Arduino.h>
#include <Mitov_ESP32.h>
int LED = 2;

// Custom Code Declarations

namespace CustomCode
{
  class TCustomCode1
  {
  public:
    void SystemInit();

  public:
    void SystemLoopBegin( unsigned long currentMicros );

  };
} // CustomCode

// Declarations

namespace Declarations
{
CustomCode::TCustomCode1 CustomCode1;
} // Declarations

// Custom Code Implementations

namespace CustomCode
{
void TCustomCode1::SystemInit()
{
pinMode(LED, OUTPUT);
}

void TCustomCode1::SystemLoopBegin( unsigned long currentMicros )
{
digitalWrite(LED, HIGH);
delay(2000);    
digitalWrite(LED, LOW);    
delay(1000);               
}

} // CustomCode

namespace ComponentsHardware
{
void SystemUpdateHardware()
{
}
} // ComponentsHardware

//The setup function is called once at startup of the sketch
void setup()
{
  Declarations::CustomCode1.SystemInit();
}

// The loop function is called in an endless loop
void loop()
{
  unsigned long A_Current_Microseconds = micros();

  Declarations::CustomCode1.SystemLoopBegin( A_Current_Microseconds );
}
